// Generated by CoffeeScript 1.8.0
(function() {
  if (!window.Yuri) {
    window.Yuri = {};
  }

  if (!Yuri.widget) {
    Yuri.widget = {};
  }

  if (!Yuri.widget["progress-bar"]) {
    Yuri.widget["progress-bar"] = {};
  }

  Yuri.widget["progress-bar"] = {
    template: "<div class=\"bar\"></div>",
    options: {
      animate: true,
      animationDuration: 200,
      value: 0
    },
    initialize: function(options) {
      this.$el = $(options.el);
      $.extend(this.options, options);
      return this.render();
    },
    render: function() {
      this.$el.addClass("yuri-progress-bar");
      this.$el.append(this.template);
      if (this.options.animate) {
        this.$el.find(".bar").css("transition", "width " + this.options.animationDuration + " ease-in-out");
      } else {
        this.$el.find(".bar").css("transition", "initial");
        this.options.animationDuration = 0;
      }
      setTimeout((function(_this) {
        return function() {
          return _this.$el.find(".bar").css("width", _this.options.value + "%");
        };
      })(this), 0);
      this.$el.find(".bar").click((function(_this) {
        return function() {
          return alert(_this.options.value);
        };
      })(this));
      return this;
    }
  };

}).call(this);
